# This is a basic workflow that is manually triggered

name: gitSync

on:
  push:
    branches: '**'
    
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: syncDistantRepo
      run:
        curl https://sae.kap.wtf/gitSync.php/
